name: Build Docker Image

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Build a docker image
      run: |
        mv token.env.sample token.env
        docker-compose build home
